---
- name: create/update stack
  cloudformation:
    stack_name: development
    state: present
    template: templates/dev.json
    template_format: json
    template_parameters:
      KeyPairName: "{{ keypairname }}"
      Email: "{{ email }}"
    tags:
      Environment: dev
  register: cf_stack

- debug: msg={{ cf_stack }}
  when: debug is defined