---
- name: create/update stack
  cloudformation:
    stack_name: deployment
    state: present
    template: templates/pipeline.json
    template_format: json
    template_parameters:
      KMSKeyArn: "{{ kmskeyarn }}"
    tags:
      Environment: dev
  register: cf_stack

- debug: msg={{ cf_stack }}
  when: debug is defined